# Generated by Django 2.2.4 on 2021-05-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='fav_by',
            field=models.ManyToManyField(related_name='fav_book', to='f_books_app.User'),
        ),
    ]
